# Identificador del proyecto en SonarQube
sonar.projectKey=fwk-poc-automatech

# Codificación de archivos fuente
sonar.sourceEncoding=UTF-8

# Carpeta donde están los tests
sonar.sources=features

# Excluir node_modules y archivos de configuración del análisis
sonar.exclusions=node_modules/**/*,**/webpack.config.js

# Excluir todos los archivos del análisis de cobertura
sonar.coverage.exclusions=**/*.js,**/*.ts

# Incluir todos los archivos de test para análisis (si deseas que se analicen como test)
sonar.test.inclusions=features/**/*.js,features/**/*.ts

# No incluir reporte de cobertura (comentado)
# sonar.javascript.lcov.reportPaths=./coverage/lcov.info
